import pyautogui
import time

waitingTime = 0.01
pyautogui.PAUSE = 0.1

time.sleep(5)
while True:
    pyautogui.typewrite("I a m t h e b u s i e s t p e n g u i n I k n o w C l e a n i n g t h e w i n d o w s a t t h e D o j o W i p i n g t h e m d o w n a n d g e t t i n g t h e m s h i n e d M a k i n g s u r e n o o n e h a s l e f t s t r e a k s b e h i n d")
    pyautogui.moveTo(1450, 860)
    time.sleep(waitingTime)
    pyautogui.click()
    pyautogui.moveTo(1451, 860)
    pyautogui.click()
    pyautogui.click()
    time.sleep(waitingTime)
    pyautogui.typewrite("T h e n o n e d a y w h i l e I w a s w o r k i n g a w a y W o u l d n ' t y o u k n o w i t , s o m e p e n g u i n s t h e y c a m e A n d b r o u g h t t h i s c o n t a i n e r a s b i g a s t h e s e a A n d f i l l e d t o t h e t o p w i t h g l o w i n g l i m e g r e e n !")
    pyautogui.moveTo(1450, 860)
    time.sleep(waitingTime)
    pyautogui.click()
    pyautogui.moveTo(1451, 860)
    pyautogui.click()
    pyautogui.click()
    time.sleep(waitingTime)
    pyautogui.typewrite("I g a z e d i n a m a z e m e n t a s t h e y f e l l i n T h e n o n e o f t h e m s p o k e t o m e w i t h a g r i n ,  I t ' s a c o l o r f u l p a r t y f o r a l l t o e x p r e s s ! B u t w h i l e h e w a s s o h a p p y , t h e p l a c e w a s a m e s s !")
    pyautogui.moveTo(1450, 860)
    time.sleep(waitingTime)
    pyautogui.click()
    pyautogui.moveTo(1451, 860)
    pyautogui.click()
    pyautogui.click()
    time.sleep(waitingTime)
    pyautogui.typewrite("T h e r e w a s p a i n t o n t h e w a l l s a n d p a i n t o n t h e c e i l i n g T h i s p a i n t - s p l a t t e r e d p l a c e made me feel like squealing! And just when I thought I could take it no more A penguin began to make tracks on the floor! ")
    pyautogui.moveTo(1450, 860)
    time.sleep(waitingTime)
    pyautogui.click()
    pyautogui.moveTo(1451, 860)
    pyautogui.click()
    pyautogui.click()
    time.sleep(waitingTime)
    pyautogui.typewrite("I just cleaned the floor! I loudly proclaimed, And now I will have to go mop it again! But wouldn't you know it, this mop that I used Was worn as a wig by a penguin in blue! ")
    pyautogui.moveTo(1450, 860)
    time.sleep(waitingTime)
    pyautogui.click()
    pyautogui.moveTo(1451, 860)
    pyautogui.click()
    pyautogui.click()
    time.sleep(waitingTime)
    pyautogui.typewrite("Now I faced a decision of just what to do My mop was unusable thanks to this crew The rags that I used were just far too worn out So I stood on that paint can and started to pout. ")
    pyautogui.moveTo(1450, 860)
    time.sleep(waitingTime)
    pyautogui.click()
    pyautogui.moveTo(1451, 860)
    pyautogui.click()
    pyautogui.click()
    time.sleep(waitingTime)
    pyautogui.typewrite("Then a penguin responded You seem so upset! It's time for a party, but did you forget? Perhaps there's a way for me to help you. And I think that I know just what we should do! ")
    pyautogui.moveTo(1450, 860)
    time.sleep(waitingTime)
    pyautogui.click()
    pyautogui.moveTo(1451, 860)
    pyautogui.click()
    pyautogui.click()
    time.sleep(waitingTime)
    pyautogui.typewrite("Then that penguin came up with an idea so great, Why use just two flippers when you can use eight? Then an octopus came to lend us a hand And at least seven more! Now, isn't that grand? ")
    pyautogui.moveTo(1450, 860)
    time.sleep(waitingTime)
    pyautogui.click()
    pyautogui.moveTo(1451, 860)
    pyautogui.click()
    pyautogui.click()
    time.sleep(waitingTime)
    pyautogui.typewrite("When the party was over, then everyone joined! They helped clean the Dojo without needing a coin. And when we were done, Then a penguin responded You seem so upset! It's time for a party, but did you forget? Perhaps there's a way for me to help you. And I think that I know just what we should do!  place was so perfect You'd never have guessed it was once a green wreck! The End ")
    pyautogui.moveTo(1450, 860)
    time.sleep(waitingTime)
    pyautogui.click()
    pyautogui.moveTo(1451, 860)
    pyautogui.click()
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(690, 860)
    pyautogui.click()
    time.sleep(0.9)
    pyautogui.moveTo(1255, 502)
    pyautogui.click()
    time.sleep(0.3)
    pyautogui.moveTo(495, 435)
    pyautogui.click()
    pyautogui.moveTo(775, 750)
    pyautogui.click()
    pyautogui.moveTo(870, 550)
    pyautogui.click()
    time.sleep(0.3)
    pyautogui.moveTo(1200, 870)
    pyautogui.click()
    pyautogui.moveTo(1451, 860)
    pyautogui.click()

